from __future__ import annotations

BUILTIN_CONNECTORS: list[dict] = [
    {
        "id": "figma",
        "name": "Figma",
        "description": "Create, edit, and inspect Figma designs. Ask Oprel to make components, update layouts, or export assets.",
        "category": "Design",
        "icon": "figma",
        "color": "#F24E1E",
        "transport": "streamable_http",
        "url": "https://mcp.figma.com/mcp",
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://www.figma.com/oauth",
            "token_url": "https://api.figma.com/v1/oauth/token",
            "scopes": ["files:read"],
            "client_id_key": "FIGMA_CLIENT_ID",
        },
        "auth_label": "Figma OAuth",
        "auth_help": "Click Connect to authenticate with Figma securely.",
        "auth_url": "https://www.figma.com/developers/api#authentication",
        "tools_preview": ["get_file", "create_component", "update_node", "export_asset"],
        "requires_package": None,
    },
    {
        "id": "canva",
        "name": "Canva",
        "description": "Create and edit Canva designs, generate images, and manage your Canva library from chat.",
        "category": "Design",
        "icon": "canva",
        "color": "#00C4CC",
        "transport": "streamable_http",
        "url": "https://mcp.canva.com/mcp",
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://www.canva.com/api/oauth/authorize",
            "token_url": "https://api.canva.com/rest/v1/oauth/token",
            "scopes": ["design:content:read", "design:content:write"],
            "client_id_key": "CANVA_CLIENT_ID",
        },
        "auth_label": "Canva OAuth",
        "auth_help": "Click Connect to authenticate with Canva.",
        "auth_url": "https://www.canva.com/developers/",
        "tools_preview": ["create_design", "get_design", "export_design"],
        "requires_package": None,
    },
    {
        "id": "notion",
        "name": "Notion",
        "description": "Read, create, and update Notion pages, databases, and blocks from chat.",
        "category": "Productivity",
        "icon": "notion",
        "color": "#000000",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@notionhq/notion-mcp-server"],
        "env_vars": {"OPENAPI_MCP_HEADERS": "{\"Authorization\": \"Bearer {api_key}\", \"Notion-Version\": \"2022-06-28\"}"},
        "auth_type": "api_key",
        "auth_label": "Notion Integration Token",
        "auth_help": "notion.so/my-integrations → New integration → copy Internal Integration Secret",
        "auth_url": "https://www.notion.so/my-integrations",
        "tools_preview": ["search", "create_page", "update_block", "query_database"],
        "requires_package": "npx",
    },
    {
        "id": "google-drive",
        "name": "Google Drive",
        "description": "Search, read, and summarise Google Docs, Sheets, and Drive files.",
        "category": "Productivity",
        "icon": "google-drive",
        "color": "#34A853",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-gdrive"],
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "scopes": ["https://www.googleapis.com/auth/drive.readonly"],
            "client_id_key": "GOOGLE_CLIENT_ID",
            "extra_params": {"access_type": "offline", "prompt": "consent"},
        },
        "auth_label": "Google Drive OAuth",
        "auth_help": "Click Connect to authenticate with Google Drive.",
        "auth_url": "https://console.cloud.google.com/apis/credentials",
        "env_vars": {"GOOGLE_ACCESS_TOKEN": "{api_key}"},
        "tools_preview": ["search_files", "read_file", "list_files"],
        "requires_package": "npx",
    },
    {
        "id": "brave-search",
        "name": "Brave Search",
        "description": "Search the web in real time without leaving Oprel. Powered by Brave Search API.",
        "category": "Web",
        "icon": "search",
        "color": "#FB542B",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-brave-search"],
        "env_vars": {"BRAVE_API_KEY": "{api_key}"},
        "auth_type": "api_key",
        "auth_label": "Brave Search API Key",
        "auth_help": "brave.com/search/api → Get started → copy API key",
        "auth_url": "https://brave.com/search/api/",
        "tools_preview": ["brave_web_search", "brave_local_search"],
        "requires_package": "npx",
    },
    {
        "id": "microsoft-word",
        "name": "Microsoft Word",
        "description": "Create, read, and edit Word documents (.docx) directly from chat.",
        "category": "Microsoft 365",
        "icon": "word",
        "color": "#2B579A",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@microsoft/mcp-server-office-word"],
        "env_vars": {"MS_GRAPH_TOKEN": "{api_key}"},
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": ["Files.ReadWrite", "offline_access"],
            "client_id_key": "AZURE_CLIENT_ID",
        },
        "auth_label": "Microsoft OAuth",
        "auth_help": "Click Connect to authenticate with Microsoft 365.",
        "auth_url": "https://portal.azure.com/",
        "tools_preview": ["create_document", "read_document", "edit_document"],
        "requires_package": "npx",
    },
    {
        "id": "microsoft-excel",
        "name": "Microsoft Excel",
        "description": "Read, write, and analyse Excel spreadsheets (.xlsx) from chat.",
        "category": "Microsoft 365",
        "icon": "excel",
        "color": "#217346",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@microsoft/mcp-server-office-excel"],
        "env_vars": {"MS_GRAPH_TOKEN": "{api_key}"},
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": ["Files.ReadWrite", "offline_access"],
            "client_id_key": "AZURE_CLIENT_ID",
        },
        "auth_label": "Microsoft OAuth",
        "auth_help": "Click Connect to authenticate with Microsoft 365.",
        "auth_url": "https://portal.azure.com/",
        "tools_preview": ["read_sheet", "write_cells", "create_chart"],
        "requires_package": "npx",
    },
    {
        "id": "microsoft-powerpoint",
        "name": "PowerPoint",
        "description": "Create and edit PowerPoint presentations (.pptx) from chat.",
        "category": "Microsoft 365",
        "icon": "powerpoint",
        "color": "#D24726",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@microsoft/mcp-server-office-powerpoint"],
        "env_vars": {"MS_GRAPH_TOKEN": "{api_key}"},
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
            "token_url": "https://login.microsoftonline.com/common/oauth2/v2.0/token",
            "scopes": ["Files.ReadWrite", "offline_access"],
            "client_id_key": "AZURE_CLIENT_ID",
        },
        "auth_label": "Microsoft OAuth",
        "auth_help": "Click Connect to authenticate with Microsoft 365.",
        "auth_url": "https://portal.azure.com/",
        "tools_preview": ["create_presentation", "add_slide", "export_pdf"],
        "requires_package": "npx",
    },
    {
        "id": "gmail",
        "name": "Gmail",
        "description": "Read, search, send, and manage Gmail messages and labels from chat.",
        "category": "Google",
        "icon": "gmail",
        "color": "#EA4335",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@gongrzhe/server-gmail-autoauth-mcp"],
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "scopes": ["https://mail.google.com/"],
            "client_id_key": "GOOGLE_CLIENT_ID",
            "extra_params": {"access_type": "offline", "prompt": "consent"},
        },
        "auth_label": "Google OAuth",
        "auth_help": "Click Connect to authenticate with Gmail.",
        "auth_url": "https://console.cloud.google.com/apis/credentials",
        "env_vars": {"GOOGLE_ACCESS_TOKEN": "{api_key}"},
        "tools_preview": ["search_emails", "send_email", "read_email", "list_labels"],
        "requires_package": "npx",
    },
    {
        "id": "google-calendar",
        "name": "Google Calendar",
        "description": "View, create, update, and delete Google Calendar events from chat.",
        "category": "Google",
        "icon": "google-calendar",
        "color": "#1A73E8",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@cocal/google-calendar-mcp"],
        "auth_type": "oauth_pkce",
        "oauth": {
            "authorize_url": "https://accounts.google.com/o/oauth2/v2/auth",
            "token_url": "https://oauth2.googleapis.com/token",
            "scopes": ["https://www.googleapis.com/auth/calendar"],
            "client_id_key": "GOOGLE_CLIENT_ID",
            "extra_params": {"access_type": "offline", "prompt": "consent"},
        },
        "auth_label": "Google OAuth",
        "auth_help": "Click Connect to authenticate with Google Calendar.",
        "auth_url": "https://console.cloud.google.com/apis/credentials",
        "env_vars": {"GOOGLE_ACCESS_TOKEN": "{api_key}"},
        "tools_preview": ["list_events", "create_event", "update_event", "delete_event"],
        "requires_package": "npx",
    },
    {
        "id": "github",
        "name": "GitHub",
        "description": "Search repos, read files, create issues, open PRs, and manage GitHub Actions from chat.",
        "category": "Development",
        "icon": "github",
        "color": "#24292F",
        "transport": "stdio",
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-github"],
        "env_vars": {"GITHUB_PERSONAL_ACCESS_TOKEN": "{api_key}"},
        "auth_type": "api_key",
        "auth_label": "GitHub Personal Access Token",
        "auth_help": "github.com → Settings → Developer settings → Personal access tokens → Fine-grained tokens → Generate",
        "auth_url": "https://github.com/settings/tokens",
        "tools_preview": ["search_repositories", "create_issue", "create_pull_request", "get_file_contents"],
        "requires_package": "npx",
    },
]

_BY_ID: dict[str, dict] = {c["id"]: c for c in BUILTIN_CONNECTORS}


def get_builtin_connector(connector_id: str) -> dict | None:
    return _BY_ID.get(connector_id)


def list_builtin_connectors() -> list[dict]:
    return BUILTIN_CONNECTORS
